package org.addario;

import java.util.List;
import java.util.Random;
import java.util.UUID;

public record Payment(String batch_id,
                      String reference_id,
                      String funding_account_id,
                      String funding_account_external_id,
                      String destination_currency,
                      String destination_country,
                      String direction,
                      String amount,
                      String payment_method,
                      String charge_code,
                      String execution_date,
                      String reference_info,
                      String funds_source,
                      String remittance_purpose,
                      String bene_identifier,
                      String bene_external_id,
                      String bene_type,
                      String company_name,
                      String first_name,
                      String middle_name,
                      String last_name,
                      String address,
                      String city,
                      String state,
                      String postal_code,
                      String country,
                      String phone,
                      String dob,
                      String nationality,
                      String email,
                      String tax_id,
                      String company_registration,
                      String passport,
                      String national_id,
                      String account_number,
                      String iban,
                      String swift_bic,
                      String bank_code_type,
                      String bank_code,
                      String bank_name,
                      String bank_address,
                      String bank_city,
                      String bank_state,
                      String bank_postal_code,
                      String bank_country,
                      String credit_type,
                      String credit_to,
                      String intermediary_switf_bic,
                      String intermediary_bank_name,
                      String intermediary_bank_address,
                      String intermediary_bank_city,
                      String intermediary_bank_state,
                      String intermediary_bank_postal_code,
                      String intermediary_bank_country,
                      String resident_type,
                      String purpose_code) {
    static Random r = new Random();
    static List<String> names = List.of("Ahmad", "Aleksandra", "Ankush", "Anton", "Bahdan", "Bessam", "Bishal",
            "Chiamaka", "Chris", "Daniel", "Dawid L", "Dawid P", "Douglas", "Ed", "Ekaterina", "Elizaveta", "Faris",
            "Guilherme", "Ian", "Iliyan", "Illia", "Jakub", "Jan", "Jędrzej", "João", "Jonathan", "Leo", "Mark", "Mateusz",
            "Mic", "Michal I", "Michal Z", "Mikołaj", "Nabeel", "Nazli", "Nicola", "Nkemjika", "Pato", "Pedro", "Rayane",
            "Reza", "Sudi", "Tuan");

    public Payment() {
        this(UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                "currency_code",
                "country",
                "direction",
                "amount",
                "payment_method",
                "charge_code",
                "execution_date",
                "reference_info",
                "funds_source",
                "remittance_purpose",
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                "bene_type",
                "company_name",
                names.get(r.nextInt(names.size())),
                "middle_name",
                "last_name",
                "address",
                "city",
                "state",
                "postal_code",
                "country",
                "phone",
                "dob",
                "nationality",
                "email",
                "tax_id",
                "company_registration",
                "passport",
                "national_id",
                "account_number",
                "iban",
                "swift_bic",
                "bank_code_type",
                "bank_code",
                "bank_name",
                "bank_address",
                "bank_city",
                "bank_state",
                "bank_postal_code",
                "bank_country",
                "credit_type",
                names.get(r.nextInt(names.size())),
                "intermediary_switf_bic",
                "intermediary_bank_name",
                "intermediary_bank_address",
                "intermediary_bank_city",
                "intermediary_bank_state",
                "intermediary_bank_postal_code",
                "intermediary_bank_country",
                "resident_type",
                "purpose_code"
        );
    }
}
